### ISSUE TITLE
デザイン作成

### ISSUE THREAD

**Issue by megane9988** [tasa-education/note-movies#2]

**Comment by miminari** [comment]
きゃーざっくりアサインされた！なんか嬉しい！はげみます！

**Comment by megane9988** [comment]
本当にざっくりざっくり課題なのでデザインチームと一緒に、デザインの課題分けを当日できればと思いますー

**Comment by Tatamize** [comment]
よろしくお願いします！
当日絶対間に合う気がしないのでとりいそぎワイヤー兼ねたデザインラフ置いてます。（トップのみ）
（こういう連絡先はどことどこに書いたらいいのだろうと思いつつ。。。）

https://www.figma.com/file/qx5uvFMTPCDefeTSEaaycL/Wire-flame-and-Raf-Design?node-id=4%3A0
