### ISSUE TITLE
Twitter関連のデザイン作成

### ISSUE THREAD

**Issue by megane9988** [tasa-education/note-movies#22]
- アイコン
- カバー画像

**Comment by nukaga** [comment]
ひとまずアイコン置いておきますー
![icon](https://user-images.githubusercontent.com/3480985/82133035-bb2f3f80-9821-11ea-8bb3-05bb783449fa.png)

これくらいの表示になります
<img width="148" alt="スクリーンショット 2020-05-17 9 34 48" src="https://user-images.githubusercontent.com/3480985/82133043-c97d5b80-9821-11ea-9c99-11fe3ac440a3.png">

https://www.figma.com/file/qx5uvFMTPCDefeTSEaaycL/Wire-frame-%26-Rough-Design?node-id=117%3A124

ノートムービーズの文字はかわいいのですがアイコンにすると読めなくなるので抜きました。真っ白に黒のアイコンでもパキッとしてて良いのですが、子ども向けを考えているとのことで少し柔らかさを出したく、サイトの方で使われているbk_lightblueを背景に、ロゴの下に薄く白を落としています。

**Comment by nukaga** [comment]
Twitter のカバー画像作りました。
楽しそう、色んな動画があるよというイメージを出したくて、賑やかめにしています。

![Twitter Header - 1](https://user-images.githubusercontent.com/3480985/82136959-55a57800-984e-11ea-9fdd-2e6631b82bbb.png)
