### ISSUE TITLE
開発環境ローカル

### ISSUE THREAD

**Issue by megane9988** [tasa-education/note-movies#23]
# Docker+wp-env
- https://ja.wordpress.org/team/handbook/block-editor/packages/packages-env/
- https://capitalp.jp/2020/05/15/head-first-wp-env/

# その他
- Mamp
    - https://www.mamp.info/
- Xampp
    - https://www.apachefriends.org/jp/index.html
- Local | Local WordPress development made simple
    - https://localwp.com/

**Comment by Shizumi** [comment]
それぞれでやることになりました！
