### ISSUE TITLE
youtubeのディスクリプションの検討

### ISSUE THREAD

**Issue by megane9988** [tasa-education/note-movies#26]
有名なYoutuberおよび、関連の同様の動画などを参考に
Yotube内の記事に埋め込むべき説明文の雛形の作成をお願いします。

**Comment by tsuyoring** [comment]
この辺りに纏めていってます。
https://docs.google.com/spreadsheets/d/12USpoZzhvwXjQscSeiNuSF1G3nJtunjACiofSQVEdOI/edit?usp=sharing
「scrutiny」シート以降(右)
