### ISSUE TITLE
カテゴリーの登録

### ISSUE THREAD

**Issue by megane9988** [tasa-education/note-movies#28]
ひとまず小学校1〜6年のカテゴリーを追加
slugをどうするかみんなで検討

@ryosuke-koda  
こちらに1年生から6年生まで登録をお願いします。
ひとまずslugは日本語でOKです。

https://note-movies.shizumi.net/nm/wp-admin/edit-tags.php?taxonomy=grade&post_type=movies

**Comment by Tatamize** [comment]
els-one 
jhs-one 
hs-one とかはどうでしょう？

**Comment by Shizumi** [comment]
1st-grade
2st-grade
ってやろうと思ったけど小学生とかでダブるよねって話になったので保留！

**Comment by Shizumi** [comment]
「学習動画」という投稿タイプに「学年」というカスタムタクソノミー追加していますのでこちらに登録してください！
「学年」というタクソノミーがふさわしいかは相談したいです！ｗ

**Comment by Shizumi** [comment]
> els-one
> jhs-one
> hs-one とかはどうでしょう？

めっちゃ良いと思います！
これでいきましょう！！！
