### ISSUE TITLE
プライバシーポリシー追加

### ISSUE THREAD

**Issue by megane9988** [tasa-education/note-movies#30]
https://docs.google.com/document/d/1M7mhRcwufbmxq2ttQYwXMrmhYx2NLSZ-/edit

**Comment by rskdako** [comment]
プライバシーポリシー原稿（https://docs.google.com/document/d/1M7mhRcwufbmxq2ttQYwXMrmhYx2NLSZ-/edit）
の1行目、「当社」という表記の件について。

NPOなどの非営利団体のプライバシーポリシーでは「当社」ではなく「当団体」、「当法人」表記が多いように見受けられる。
各団体によってそれぞれ表記は異なるが、ターサーエデュケーション様としてはどの表記を選ばれるか確認させていただきたい。
