### ISSUE TITLE
動画記事作成

### ISSUE THREAD

**Issue by tsuyoring** [tasa-education/note-movies#34]
投稿データリスト
https://docs.google.com/spreadsheets/d/1lwyPeVRpw7sauqMixx38nq1l37wdQ_4MQd8TrENExQg/edit#gid=1368523787
thumbnailジェネレータ
https://html-css-javascript.com/youtube-thumb/

**Comment by rskdako** [comment]
小学１年生から小学６年生まで、完了です。
