### ISSUE TITLE
開発環境共有(リモート)

### ISSUE THREAD

**Issue by megane9988** [tasa-education/note-movies#4]

**Comment by Shizumi** [comment]
https://docs.google.com/document/d/1Cb0YURY0ATHA5xGcE8p-I9lpL73Nb4mUkONZ24ut5Ss/edit?usp=sharing
テストサーバについてこちらのドキュメントに記載しました。

**Comment by Shizumi** [comment]
テストサーバのWordPressについては明日の作業開始までにバニラインストールまではしておきます。

**Comment by Shizumi** [comment]
テストサーバへのWordPressインストール完了しています。
ログイン情報については [こちら](https://docs.google.com/document/d/1Cb0YURY0ATHA5xGcE8p-I9lpL73Nb4mUkONZ24ut5Ss/edit?usp=sharing) に記載しています。
