### ISSUE TITLE
カテゴリーごとに説明文を入れる

### ISSUE THREAD

**Issue by megane9988** [tasa-education/note-movies#54]
何かしらのルールを決めて挿入をお願いします。
こちらが、カテゴリーアーカイブのディスクリプションとなります。

**Comment by tsuyoring** [comment]
<img width="1229" alt="スクリーンショット 2020-05-17 11 47 13" src="https://user-images.githubusercontent.com/3218637/82134617-6648f480-9834-11ea-9e20-d6865d767fa2.png">
こんな感じです？
