### ISSUE TITLE
トップページの「学年選択ボタン」の表示崩れ（iPhone8）

### ISSUE THREAD

**Issue by rskdako** [tasa-education/note-movies#64]
[トップページ](https://note-movies.com)の学年を選ぶボタンの表示がずれています。
![スクリーンショット 2020-05-17 15 42 41](https://user-images.githubusercontent.com/43376374/82137665-19c1e100-9855-11ea-9bb3-7f500400d093.png)

**Comment by megane9988** [comment]
![image](https://user-images.githubusercontent.com/1205958/82143133-7e446680-987c-11ea-9a11-362620e2f2d1.png)

一列に修正されていることを確認！
