### ISSUE TITLE
トップページの運営会社エリア：ロゴの上の文字の中央揃え（スマホ）

### ISSUE THREAD

**Issue by tsuyoring** [tasa-education/note-movies#67]
スマホで見たときにターサのロゴの上の
NPO法人ターサ•エデュケーションの文字を中央に揃えてもらえるとありがたいです(by市村さん)

![iOS の画像](https://user-images.githubusercontent.com/3218637/82137910-13ccff80-9857-11ea-9f29-b1aa9a6acd61.png)

**Comment by megane9988** [comment]
https://note-movies.com/
中央寄せDone!
みてもらってOKならCloseしてください。
@tsuyoring
